{{--start--}}
@extends('layouts.app')
@section('content')
@guest
     @include('guest.welcome')
    {{--@include('guest\one')--}}
    @else
    @include('logged.welcome')
@endguest
@endsection
{{--end--}}
